version: '2'
services:
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://gateway-mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://gateway-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://gateway-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'
  gateway-mysql:
    image: 'mysql:8.0.16'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gateway
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  gateway-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  member-app:
    image: member
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://member-mysql:3306/member?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://member-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://member-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
  member-mysql:
    image: 'mysql:8.0.16'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=member
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  member-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  wallet-app:
    image: wallet
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://wallet-mysql:3306/wallet?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://wallet-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://wallet-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
  wallet-mysql:
    image: 'mysql:8.0.16'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=wallet
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  wallet-elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.4.3'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
